name: Valia Calda Hotel
favicon: null
layout_spectrum: 0.24357
typography_spectrum: 0.50391
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2e0e01'
    - '#816c29'
    - '#b5a567'
    - '#9e8c42'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
