name: Valia Calda Hotel
favicon: null
layout_spectrum: 0.7793908554594964
typography_spectrum: 0.5084583214484155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6286703944206238
  lightness: 0.9177123229019344
  saturation: 0.4725438633468002
  rhythmicContrast: 0.043742116540670395
purpose: []
