name: Valia Calda Hotel
favicon: null
layout_spectrum: 0.24357
typography_spectrum: 0.50391
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0ecc7'
    - '#4f3e36'
    - '#786f60'
    - '#a39e88'
    - '#bcb69c'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
